### ISSUE TITLE
The pathfinder 2e ruleset hasn't been udpates for V11..

### ISSUE THREAD

**Issue by Mermut** [BernhardPosselt/pf2e-kingmaker-map-remake#2]
This module is to support a pathfinder 2e AP. The pathfinder 2e ruleset hasn't been updated for Foundry v11. 
This module has removed support for v10 and is only v11....
This makes the 'new' maps unavailble...

**Comment by BernhardPosselt** [comment]
Yes this will resolve itself once the 2e module comes out which should be a matter of 1-3 weeks I think. Keeping this open to catch similar complaints

There's unfortunately not an easy way to keep compatibility.

**Comment by Mermut** [comment]
Part of the reason I mentioned it because the update explicitly removed v10 compatibility. There are quite a few mods that have been updated to v11 but not removed v10 compatibility.

**Comment by BernhardPosselt** [comment]
FoundryVTT broke all compendia in V11 so I can't keep compatibility.

**Comment by BernhardPosselt** [comment]
v11 2e release is out, so closing this issue.
